name: sasApp
services:
  sasApp-db:
    image: mariadb:11.3.2
    container_name: sasApp-db
    environment:
      MARIADB_DATABASE: sasApp_database
      MARIADB_USER: sasApp_user
      MARIADB_PASSWORD: sasApp_password
      MARIADB_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    healthcheck:
      test: [ CMD, healthcheck.sh, --connect, --innodb_initialized ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - network-sasApp

  sasApp-api:
    image: sas-app-api
    container_name: sas-app-api
    ports:
      - "8086:8086"
    depends_on:
      sasApp-db:
        condition: service_healthy
    environment:
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_APPLICATION_JSON: '{
    "spring.application.name": "sasApp",
        "server.port": "8086",
        "spring.datasource.url": "jdbc:mariadb://sasApp-db:3306/sasApp_database",
        "spring.datasource.username": "sasApp_user",
        "spring.datasource.password": "sasApp_password",
        "spring.jpa.database-platform": "org.hibernate.dialect.MariaDBDialect",
        "application.security.jwt.secret-key": "PracticasPResencialesMayo2026SocialAssistanceServiceApplication",
        "application.security.jwt.expiration": 86400000,
        "application.security.jwt.refresh-token.expiration": 604800000,
        "spring.jpa.show-sql": true,
        "spring.jpa.properties.hibernate.format_sql": true,
        "logging.level.org.springframework": "DEBUG"
      }'
    networks:
      - network-sasApp
networks:
  network-sasApp:
    driver: bridge