spring.application.name=sasApp


application.security.jwt.secret-key=PracticasPResencialesMayo2026SocialAssistanceServiceApplication
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000