spring.application.name=sasApp
server.port=8086

spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.datasource.url=jdbc:mariadb://localhost:3307/${MYSQL_DATABASE}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

application.security.jwt.secret-key=PracticasPResencialesMayo2026SocialAssistanceServiceApplication
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework=DEBUG